/* Gestionar la base de datos */
-- Borrar base de datos
DROP DATABASE IF EXISTS ZAPATERIA;

-- Crear base de datos
CREATE DATABASE ZAPATERIA
DEFAULT CHARACTER SET utf8;

-- Poner en uso la base de datos
USE ZAPATERIA;

-- Ver cual es la base de datos en uso
SELECT DATABASE();

/* Crear tablas */

-- Crear tabla CLIENTE
CREATE TABLE CLIENTE (
    CODCLI char(4),
    NOMCLI varchar(50),
    APECLI varchar(50),
    DIRCLI varchar(50),
    FECNACCLI date,
    SEXCLI char(1),
    CELCLI char(9),
    DNICLI char(8),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CODCLI)
);

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO (
    CODEMP char(4),
    NOMEMP varchar(50),
    APEEMP varchar(50),
    DIREMP varchar(50),
    FECNACEMP date,
    SEXEMP char(1),
    CELEMP char(9),
    DNIEMP char(8),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (CODEMP)
);

-- Crear tabla MARCA
CREATE TABLE MARCA (
    CODMAR char(4),
    NOMMAR char(50),
    CONSTRAINT MARCA_PK PRIMARY KEY (CODMAR)
);

-- Crear tabla PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO char(4),
    COLPRO varchar(50),
    TALPRO char(2),
    PREPRO decimal(10,2),
    TIPPRO varchar(50),
    SOTPRO char(4),
    CODMAR char(4),
    CODPROV char(4),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (CODPRO)
);

-- Crear tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
    CODPROV char(4),
    NOMPROV varchar(50),
    APEPROV varchar(50),
    DIRPROV varchar(50),
    FECNACPROV date,
    SEXPROV char(1),
    CELPROV char(9),
    DNIPROV char(8),
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (CODPROV)
);

-- Crear tabla VENTA
CREATE TABLE VENTA (
    CODVEN char(4),
    FECVEN date,
    CODCLI char(4),
    CODEMP char(4),
    CONSTRAINT VENTA_PK PRIMARY KEY (CODVEN)
);

-- Crear tabla VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    CODVENDET char(4),
    CANVENDET char(4),
    CODPRO char(4),
    CODVEN char(4),
    CONSTRAINT VENTA_DETALLE_PK PRIMARY KEY (CODVENDET)
);

SHOW TABLES;

/* Crear las relaciones */

-- Relacionar la tabla EMPLEADO - VENTA
ALTER TABLE VENTA
ADD CONSTRAINT EMPLEADOS_VENTA_CODEMP
FOREIGN KEY (CODEMP) REFERENCES EMPLEADO (CODEMP);

-- Relacionar la tabla CLIENTE - VENTA
ALTER TABLE VENTA
ADD CONSTRAINT CLIENTE_VENTA_CODCLI
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

-- Relacionar la tabla MARCA - PRODUCTO
ALTER TABLE PRODUCTO
ADD CONSTRAINT MARCA_PRODUCTO_CODMAR
FOREIGN KEY (CODMAR) REFERENCES MARCA (CODMAR);

-- Relacionar la tabla PROVEEDOR - PRODUCTO
ALTER TABLE PRODUCTO 
ADD CONSTRAINT PROVEEDOR_PRODUCTO_CODPROV
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV);

-- Relacionar la tabla PRODUCTO - VENTA_DETALLE
ALTER TABLE VENTA_DETALLE 
ADD CONSTRAINT PRODUCTO_VENTA_DETALLE_CODPRO
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

-- Relacionar la tabla VENTA - VENTA_DETALLE
ALTER TABLE VENTA_DETALLE 
ADD CONSTRAINT VENTA_VENTA_DETALLE_CODVEN 
FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN);

-- Listar las relaciones entre tablas
SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE table_schema="ZAPATERIA" 
    AND constraint_type="FOREIGN KEY";
